### ISSUE TITLE
 unexpected '$' after 'CHILD_SELECTOR' (Nokogiri::CSS::SyntaxError)

### ISSUE THREAD

**Issue by benwoodward** [aanand/deadweight#25]
How do I debug this?

```
/Users/benwoodward/.rbenv/versions/2.1.2/gemsets/global/gems/nokogiri-1.6.2.1/lib/nokogiri/css/parser_extras.rb:87:in `on_error': unexpected '$' after 'CHILD_SELECTOR' (Nokogiri::CSS::SyntaxError)
    from /Users/benwoodward/.rbenv/versions/2.1.2/lib/ruby/2.1.0/racc/parser.rb:258:in `_racc_do_parse_c'
    from /Users/benwoodward/.rbenv/versions/2.1.2/lib/ruby/2.1.0/racc/parser.rb:258:in `do_parse'
    from /Users/benwoodward/.rbenv/versions/2.1.2/gemsets/global/gems/nokogiri-1.6.2.1/lib/nokogiri/css/parser_extras.rb:62:in `parse'
    from /Users/benwoodward/.rbenv/versions/2.1.2/gemsets/global/gems/nokogiri-1.6.2.1/lib/nokogiri/css/parser_extras.rb:79:in `xpath_for'
    from /Users/benwoodward/.rbenv/versions/2.1.2/gemsets/global/gems/nokogiri-1.6.2.1/lib/nokogiri/css.rb:23:in `xpath_for'
    from /Users/benwoodward/.rbenv/versions/2.1.2/gemsets/global/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/node.rb:106:in `block in search'
    from /Users/benwoodward/.rbenv/versions/2.1.2/gemsets/global/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/node.rb:104:in `map'
    from /Users/benwoodward/.rbenv/versions/2.1.2/gemsets/global/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/node.rb:104:in `search'
    from /Users/benwoodward/.rbenv/versions/2.1.2/gemsets/global/gems/deadweight-0.2.2/lib/deadweight.rb:40:in `block in analyze'
    from /Users/benwoodward/.rbenv/versions/2.1.2/gemsets/global/gems/deadweight-0.2.2/lib/deadweight.rb:33:in `collect'
    from /Users/benwoodward/.rbenv/versions/2.1.2/gemsets/global/gems/deadweight-0.2.2/lib/deadweight.rb:33:in `analyze'
    from /Users/benwoodward/.rbenv/versions/2.1.2/gemsets/global/gems/deadweight-0.2.2/lib/deadweight.rb:131:in `process!'
    from /Users/benwoodward/.rbenv/versions/2.1.2/gemsets/global/gems/deadweight-0.2.2/lib/deadweight.rb:118:in `block in run'
    from /Users/benwoodward/.rbenv/versions/2.1.2/gemsets/global/gems/deadweight-0.2.2/lib/deadweight.rb:95:in `each'
    from /Users/benwoodward/.rbenv/versions/2.1.2/gemsets/global/gems/deadweight-0.2.2/lib/deadweight.rb:95:in `run'
    from /Users/benwoodward/.rbenv/versions/2.1.2/gemsets/global/gems/deadweight-0.2.2/lib/deadweight/cli.rb:113:in `process'
    from /Users/benwoodward/.rbenv/versions/2.1.2/gemsets/global/gems/deadweight-0.2.2/lib/deadweight/cli.rb:88:in `execute!'
    from /Users/benwoodward/.rbenv/versions/2.1.2/gemsets/global/gems/deadweight-0.2.2/lib/deadweight/cli.rb:19:in `execute'
    from /Users/benwoodward/.rbenv/versions/2.1.2/gemsets/global/gems/deadweight-0.2.2/bin/deadweight:4:in `<top (required)>'
    from /Users/benwoodward/.rbenv/versions/2.1.2/gemsets/global/bin/deadweight:23:in `load'
    from /Users/benwoodward/.rbenv/versions/2.1.2/gemsets/global/bin/deadweight:23:in `<main>'
```

**Comment by SimonTurner0** [comment]
I also have Nokogiri::CSS::SyntaxError: unexpected '"' after 'prefix_match'.    Any other gems out there for removing CSS selectors or is this the only one?

**Comment by jirutka** [comment]
@SimonTurner0 I’ve used [mincss](https://github.com/peterbe/mincss) instead, but it’s written in Python.

**Comment by rikas** [comment]
+1

**Comment by tomoyuki28jp** [comment]
+1

**Comment by altherlex** [comment]
+1
